apiVersion: v1
kind: Service
metadata:
  name: image-service
spec:
  selector:
    app: image
  ports:
  - port: 8005
    targetPort: 5005
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
    spec:
      containers:
      - name: image
        image: wuwanga/image:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
          requests:
            memory: "500Mi"

        ports:
        - containerPort: 5005
        readinessProbe:
        httpGet:
          path: /
          port: 5005
        initialDelaySeconds: 10
        timeoutSeconds: 60
        periodSeconds: 10
        failureThreshold: 3
