apiVersion: apps/v1
kind: Deployment
metadata:
  name: attack-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attack-server
  template:
    metadata:
      labels:
        app: attack-server
    spec:
      containers:
      - name: attack
        image: wuwanga/attack:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "500m"

        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: attack-server
spec:
  selector:
    app: attack-server
  ports:
  - port: 7000
    targetPort: 5000
  type: LoadBalancer
  externalIPs:
  - 192.168.0.165
