apiVersion: v1
kind: Service
metadata:
  name: measurement-service
spec:
  selector:
    app: measurement
  ports:
  - port: 8007
    targetPort: 5007
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: measurement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: measurement
  template:
    metadata:
      labels:
        app: measurement
    spec:
      containers:
      - name: measurement
        image: wuwanga/measurement:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
          requests:
            memory: "500Mi"

        ports:
        - containerPort: 5007
        readinessProbe:
          httpGet:
            path: /status
            port: 5007
          initialDelaySeconds: 10
          timeoutSeconds: 60
          periodSeconds: 10
          failureThreshold: 3
