apiVersion: apps/v1
kind: Deployment
metadata:
  name: victim-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victim-server
  template:
    metadata:
      labels:
        app: victim-server
    spec:
      containers:
      - name: victim
        image: wuwanga/victim:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "500m"

        ports:
        - containerPort: 5001

---

apiVersion: v1
kind: Service
metadata:
  name: victim-server
spec:
  selector:
    app: victim-server
  ports:
  - port: 8000
    targetPort: 5001
  type: LoadBalancer
  externalIPs:
  - 192.168.0.165
